theme: minima
title: sacredstarfamily
author: sacredstarfamily
email: seeloveinfinite@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 Livin life and lovin it
theme: minima
# social links
twitter_username: maykinfund # DO NOT include the @ character, or else the build will fail!
github_username:  sacredstarfamily # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
